export const ShopData = [
  {
    "name": "GreenMart",
    "image": ["https://source.unsplash.com/300x200/?shop"],
    "type": "Retail",
    "category": "Grocery",
    "address": "1st Main, Indiranagar, Bangalore - 560038",
    "about": "Your one-stop shop for fresh and organic groceries.",
    "openTill": "08:30 PM",
    "onlinePayments": true,
    "phoneNumber": "7890123450",
    "email": "greenmart@example.com",
    "features": ["Parking", "Delivery", "Dine-in", "Take Away", "Air Conditioned"]
  },
  {
    "name": "TechZone",
    "image": ["https://source.unsplash.com/300x200/?store"],
    "type": "Wholesale",
    "category": "Electronics",
    "address": "Lamington Road, Grant Road, Mumbai - 400007",
    "about": "Your go-to destination for the latest in electronics.",
    "openTill": "09:00 PM",
    "onlinePayments": false,
    "phoneNumber": "8976543210",
    "email": "techzone@example.com",
    "features": ["Delivery", "Take Away"]
  },
  {
    "name": "FashionBazaar",
    "image": ["https://source.unsplash.com/300x200/?boutique"],
    "type": "Retail",
    "category": "Apparel",
    "address": "Janpath, Connaught Place, Delhi - 110001",
    "about": "Discover the latest fashion trends at FashionBazaar.",
    "openTill": "10:30 PM",
    "onlinePayments": true,
    "phoneNumber": "8765432100",
    "email": "fashionbazaar@example.com",
    "features": ["Parking", "Delivery", "Dine-in"]
  },
  {
    "name": "FreshDeals",
    "image": ["https://source.unsplash.com/300x200/?grocery"],
    "type": "Wholesale",
    "category": "Produce",
    "address": "New Market, Esplanade, Kolkata - 700087",
    "about": "Wholesale deals on fresh produce for your business.",
    "openTill": "08:00 PM",
    "onlinePayments": true,
    "phoneNumber": "7890654320",
    "email": "freshdeals@example.com",
    "features": ["Delivery", "Take Away", "Air Conditioned"]
  },
  {
    "name": "BookNook",
    "image": ["https://source.unsplash.com/300x200/?bookstore"],
    "type": "Retail",
    "category": "Books",
    "address": "Anna Salai, Mount Road, Chennai - 600002",
    "about": "Immerse yourself in a world of books at BookNook.",
    "openTill": "09:45 PM",
    "onlinePayments": false,
    "phoneNumber": "8901234560",
    "email": "booknook@example.com",
    "features": ["Parking", "Dine-in", "Take Away"]
  },
  {
    "name": "SportsWorld",
    "image": ["https://source.unsplash.com/300x200/?sportsstore"],
    "type": "Retail",
    "category": "Sports",
    "address": "Abids, Hyderabad - 500001",
    "about": "Your destination for top-quality sports equipment.",
    "openTill": "08:15 PM",
    "onlinePayments": true,
    "phoneNumber": "8765091230",
    "email": "sportsworld@example.com",
    "features": ["Parking", "Delivery"]
  },
  {
    "name": "HomeEssentials",
    "image": ["https://source.unsplash.com/300x200/?homedecor"],
    "type": "Wholesale",
    "category": "Home Goods",
    "address": "Fergusson College Road, Pune - 411004",
    "about": "Wholesale home essentials for a cozy living space.",
    "openTill": "10:00 PM",
    "onlinePayments": false,
    "phoneNumber": "8907654320",
    "email": "homeessentials@example.com",
    "features": ["Delivery", "Take Away", "Air Conditioned"]
  },
  {
    "name": "PetParadise",
    "image": ["https://source.unsplash.com/300x200/?petstore"],
    "type": "Retail",
    "category": "Pet Supplies",
    "address": "C.G. Road, Ahmedabad - 380009",
    "about": "Everything your pet needs at PetParadise.",
    "openTill": "09:30 PM",
    "onlinePayments": true,
    "phoneNumber": "8765012340",
    "email": "petparadise@example.com",
    "features": ["Parking", "Dine-in", "Take Away"]
  },
  {
    "name": "AutoEmporium",
    "image": ["https://source.unsplash.com/300x200/?automotive"],
    "type": "Wholesale",
    "category": "Automotive",
    "address": "MI Road, Jaipur - 302001",
    "about": "Wholesale automotive parts and accessories.",
    "openTill": "08:45 PM",
    "onlinePayments": false,
    "phoneNumber": "8902345670",
    "email": "autoemporium@example.com",
    "features": ["Delivery", "Take Away"]
  },
  {
    "name": "CafeBliss",
    "image": ["https://source.unsplash.com/300x200/?cafe"],
    "type": "Retail",
    "category": "Café",
    "address": "Hazratganj, Lucknow - 226001",
    "about": "Indulge in the blissful ambiance and coffee at CafeBliss.",
    "openTill": "09:15 PM",
    "onlinePayments": true,
    "phoneNumber": "8908765430",
    "email": "cafebliss@example.com",
    "features": ["Parking", "Dine-in", "Take Away", "Air Conditioned"]
  },
  {
    "name": "OrganicHarbor",
    "image": ["https://source.unsplash.com/300x200/?organic"],
    "type": "Retail",
    "category": "Organic",
    "address": "4th Cross, Malleshwaram, Bangalore - 560055",
    "about": "Explore the organic goodness at OrganicHarbor.",
    "openTill": "09:30 PM",
    "onlinePayments": false,
    "phoneNumber": "8905678910",
    "email": "organicharbor@example.com",
    "features": ["Parking", "Delivery", "Take Away"]
  },
  {
    "name": "GizmoGallery",
    "image": ["https://source.unsplash.com/300x200/?gadgets"],
    "type": "Retail",
    "category": "Electronics",
    "address": "Linking Road, Bandra, Mumbai - 400050",
    "about": "Discover the latest gadgets at GizmoGallery.",
    "openTill": "08:30 PM",
    "onlinePayments": true,
    "phoneNumber": "8904567890",
    "email": "gizmogallery@example.com",
    "features": ["Delivery", "Take Away"]
  },
  {
    "name": "TrendyThreads",
    "image": ["https://source.unsplash.com/300x200/?fashion"],
    "type": "Retail",
    "category": "Apparel",
    "address": "Sarojini Nagar, Delhi - 110023",
    "about": "Stay in style with the latest trends at TrendyThreads.",
    "openTill": "10:00 PM",
    "onlinePayments": false,
    "phoneNumber": "8901098760",
    "email": "trendythreads@example.com",
    "features": ["Parking", "Dine-in", "Take Away"]
  },
  {
    "name": "FreshHarvest",
    "image": ["https://source.unsplash.com/300x200/?farmersmarket"],
    "type": "Wholesale",
    "category": "Produce",
    "address": "Salt Lake, Sector V, Kolkata - 700091",
    "about": "Wholesale fresh produce for your business at FreshHarvest.",
    "openTill": "08:15 PM",
    "onlinePayments": true,
    "phoneNumber": "8902345670",
    "email": "freshharvest@example.com",
    "features": ["Delivery", "Take Away"]
  },
  {
    "name": "BookwormHaven",
    "image": ["https://source.unsplash.com/300x200/?bookshop"],
    "type": "Retail",
    "category": "Books",
    "address": "Nungambakkam, Chennai - 600034",
    "about": "Dive into the world of books at BookwormHaven.",
    "openTill": "09:45 PM",
    "onlinePayments": true,
    "phoneNumber": "8908765430",
    "email": "bookwormhaven@example.com",
    "features": ["Parking", "Dine-in", "Take Away", "Air Conditioned"]
  },
  {
    "name": "ActiveZone",
    "image": ["https://source.unsplash.com/300x200/?sportsoutlet"],
    "type": "Retail",
    "category": "Sports",
    "address": "Banjara Hills, Hyderabad - 500034",
    "about": "Get active with the latest sports gear at ActiveZone.",
    "openTill": "08:30 PM",
    "onlinePayments": false,
    "phoneNumber": "8905012340",
    "email": "activezone@example.com",
    "features": ["Delivery", "Take Away"]
  },
  {
    "name": "CozyHome",
    "image": ["https://source.unsplash.com/300x200/?homedecorstore"],
    "type": "Wholesale",
    "category": "Home Goods",
    "address": "Kothrud, Pune - 411038",
    "about": "Transform your home into a cozy haven with CozyHome.",
    "openTill": "10:15 PM",
    "onlinePayments": true,
    "phoneNumber": "8905678900",
    "email": "cozyhome@example.com",
    "features": ["Parking", "Delivery", "Dine-in"]
  },
 
]